# Runs unit tests on the Neotron XXX BIOS

on: [push, pull_request]

name: Unit Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test

